highlighter: rouge
permalink: pretty
markdown: kramdown

title: Fortran Programming Language
description: "Fortran Programming Language"
languages: ["en", "fr"]

news:
    name: Fortran Newsletter
    authors: Fortran Community
    url: /news
    feed: /news.xml

url: "https://fortran-lang.org"

exclude_from_localizations: ["assets"]

plugins:
  - jekyll-multiple-languages-plugin

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
